services:
  - type: web
    name: fb-auto-backend
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm run render-start"
    envVars:
      - key: PAGE_ACCESS_TOKEN
        sync: false
      - key: VERIFY_TOKEN
        sync: false
      - key: APP_SECRET
        sync: false
      - key: GRAPH_VERSION
        value: v21.0
      - key: ALLOW_ORIGIN
        value: "*"
